import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import vm from 'node:vm';
import ts from 'typescript';
import { strFromU8, strToU8, unzipSync, zipSync } from 'fflate';
const root = new URL('../', import.meta.url);
test('兩頁 39 球標、48 規格填回客戶原表，保留量測公式及其餘工作表', async () => {
 const page = await readFile(new URL('app/page.tsx', root), 'utf8');
 const rows = JSON.parse(await readFile(new URL('app/customer-review.json', root), 'utf8'));
 assert.equal(Object.keys(rows).length,39);
 assert.equal(Object.values(rows).flat().length,48);
 const template = await readFile(new URL('public/ai-vision-customer-template.xlsx',root));
 const code = page.slice(page.indexOf('function escapeExcelXml'),page.indexOf('async function downloadReviewWorkbook'));
 const context = {strFromU8,strToU8,unzipSync,zipSync,fetch:async()=>({ok:true,arrayBuffer:async()=>template})};
 vm.createContext(context);vm.runInContext(ts.transpile(code+';globalThis.build=buildReviewWorkbook;',{target:ts.ScriptTarget.ES2022}),context);
 const fields=Object.values(rows).map(details=>({details}));
 fields[0].details[0].value='71.25';
 rows['p2-balloon-15'][0].upper='0.05';
 rows['p2-balloon-16'][2].value='<不可破孔 & 確認>';
 const files=unzipSync(await context.build(fields)),original=unzipSync(template);
 assert.deepEqual(Object.keys(files).sort(),Object.keys(original).sort());
 for(const name of Object.keys(original))if(!['xl/worksheets/sheet1.xml','xl/workbook.xml'].includes(name))assert.deepEqual(files[name],original[name],name);
 const xml=strFromU8(files['xl/worksheets/sheet1.xml']);
 assert.match(xml,/<c r="E26"[^>]*><v>71.25<\/v>/);
 assert.match(xml,/<c r="H44"[^>]*><v>0.05<\/v>/);
 assert.match(xml,/&lt;不可破孔 &amp; 確認&gt;/);
 const preservedCells=x=>[...x.matchAll(/<c\b[^>]*?(?:\/>|>[\s\S]*?<\/c>)/g)].map(m=>m[0]).filter(cell=>{const ref=cell.match(/r="([A-Z]+)(\d+)"/);return !ref || !['D','E','F','H','J'].includes(ref[1]) || Number(ref[2])<26 || Number(ref[2])>73;});
 assert.deepEqual(preservedCells(xml),preservedCells(strFromU8(original['xl/worksheets/sheet1.xml'])));
 const formulas=x=>[...x.matchAll(/<f\b[^>]*?(?:\/>|>[\s\S]*?<\/f>)/g)].map(m=>m[0]);
 assert.deepEqual(formulas(xml),formulas(strFromU8(original['xl/worksheets/sheet1.xml'])));
 assert.match(strFromU8(files['xl/workbook.xml']),/fullCalcOnLoad="1"/);
 assert.match(page,/disabled=\{exporting \|\| !allConfirmed\}/);
 assert.match(page,/pageFields.map/);
 assert.match(page,/next.page !== activeField.page/);
});
